language: node_js
node_js:
  - "8"
cache:
  directories:
    - "node_modules"

install:
  - npm install
  - npm run generate

deploy:
  provider: pages
  local-dir: dist
  skip-cleanup: true
  target-branch: master
  github-token: $GITHUB_API_KEY
  on:
    branch: develop
    condition: $TRAVIS_PULL_REQUEST == false
  fqdn: i-do-not-stand-by-in-the-presence-of-evil.com

notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
